name: 'sfdx'

on: [push]

jobs:
  Deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2              
      - name: Write the token into a file
        run: 'echo ${{ secrets.DEVHUB_TOKEN}} > token.txt'
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      - name: 'Installing java '
        run: |
            sudo apt-get update
            sudo apt install default-jdk
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"  
      - name: Cache node modules
        uses: actions/cache@v3
        id: npm_cache_id
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-cache-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.npm_cache_id.outputs.cache-hit != 'true'
        run: npm install
      - name: Authentication to PROD
        run: |
          echo "${SERVER_KEY_PASSWORD}" > server.key
          node_modules/sfdx-cli/bin/run auth:jwt:grant --clientid ${{ secrets.3MVG9ux34Ig8G5eoXfCnFXJOqQgIuqaB3Kx4mdXAxbnWvSAUv4_Egucb.46hctMtWWiuiK3PkhLn8_CWCwIJe }} --jwtkeyfile server.key --username ${{ secrets.prashantd79795@gmail.com }} --setdefaultdevhubusername --setalias prod
        env:
         SERVER_KEY_PASSWORD: ${{ secrets.12345 }}
 
       
          

