name: 'sfdx'

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2              
      - name: Write the token into a file
        run: 'echo ${{ secrets.DEVHUB_TOKEN}} > token.txt'
      - name: Install Salesforce CLI
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
          ./sfdx-cli/install
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      - name: 'Installing java'
        run: |
            sudo apt-get update
            sudo apt install default-jdk
      - name: 'Update sfdx-project.json and README'
        id: packaging-updater
        uses: muenzpraeger/github-action-sfdx-packaging-updater@master            
